steps:
  - label: "Run Benchmarks"
    agents:
      queue: "default"
    env:
      VLLM_CPU_KVCACHE_SPACE: 10
      HF_TOKEN: "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" # Replace with your actual token if required
    commands:

      - cd /root/ODH-vllm/vllm
      - eval "$(conda shell.bash hook)"
      - conda activate torch
      - export LD_LIBRARY_PATH=/root/vllm_latest_changes/vllm/OpenBLAS:$LD_LIBRARY_PATH
      - bash .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh

